//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : Stock
	/// Data Source    : Stock
	/// Server Version : 3.24.0
	/// </summary>
	public partial class StockDB : LinqToDB.Data.DataConnection
	{
		public ITable<Capital>       Capitals       { get { return this.GetTable<Capital>(); } }
		public ITable<Listed>        Listeds        { get { return this.GetTable<Listed>(); } }
		public ITable<ListedAlert>   ListedAlerts   { get { return this.GetTable<ListedAlert>(); } }
		public ITable<ListedBuySell> ListedBuySells { get { return this.GetTable<ListedBuySell>(); } }
		public ITable<OTC>           Otcs           { get { return this.GetTable<OTC>(); } }
		public ITable<OTCAlert>      OTCAlerts      { get { return this.GetTable<OTCAlert>(); } }
		public ITable<OTCBuySell>    OTCBuySells    { get { return this.GetTable<OTCBuySell>(); } }

		public StockDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public StockDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public StockDB(LinqToDbConnectionOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public StockDB(LinqToDbConnectionOptions<StockDB> options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table("Capital")]
	public partial class Capital
	{
		[Column, Nullable] public string Date         { get; set; } // varchar(32)
		[Column, Nullable] public string Name         { get; set; } // varchar(32)
		[Column, Nullable] public string FirstCapital { get; set; } // varchar(32)
		[Column, Nullable] public string NowCapital   { get; set; } // varchar(32)
		[Column, Nullable] public string Id           { get; set; } // varchar(32)
	}

	[Table("Listed")]
	public partial class Listed
	{
		[Column, Nullable] public string Date           { get; set; } // varchar(32)
		[Column, Nullable] public string Type           { get; set; } // varchar(32)
		[Column, Nullable] public string Id             { get; set; } // varchar(32)
		[Column, Nullable] public string Name           { get; set; } // varchar(32)
		[Column, Nullable] public string DealVolume     { get; set; } // varchar(32)
		[Column, Nullable] public string DealNums       { get; set; } // varchar(32)
		[Column, Nullable] public string DealPrice      { get; set; } // varchar(32)
		[Column, Nullable] public string Open           { get; set; } // varchar(32)
		[Column, Nullable] public string High           { get; set; } // varchar(32)
		[Column, Nullable] public string Low            { get; set; } // varchar(32)
		[Column, Nullable] public string Close          { get; set; } // varchar(32)
		[Column, Nullable] public string UpDown         { get; set; } // varchar(32)
		[Column, Nullable] public string Pircedif       { get; set; } // varchar(32)
		[Column, Nullable] public string LastBuyPrice   { get; set; } // varchar(32)
		[Column, Nullable] public string LastBuyVolume  { get; set; } // varchar(32)
		[Column, Nullable] public string LastSellPrice  { get; set; } // varchar(32)
		[Column, Nullable] public string LastSellVolume { get; set; } // varchar(32)
		[Column, Nullable] public string PEratio        { get; set; } // varchar(32)
		[Column, Nullable] public string NowCapital     { get; set; } // varchar(32)
		[Column, Nullable] public string TurnoverRate   { get; set; } // varchar(32)
	}

	[Table("ListedAlert")]
	public partial class ListedAlert
	{
		[Column, Nullable] public string Date { get; set; } // varchar(32)
		[Column, Nullable] public string Type { get; set; } // varchar(32)
		[Column, Nullable] public string Id   { get; set; } // varchar(32)
		[Column, Nullable] public string Name { get; set; } // varchar(32)
	}

	[Table("ListedBuySell")]
	public partial class ListedBuySell
	{
		[Column, Nullable] public string Date     { get; set; } // varchar(32)
		[Column, Nullable] public string Type     { get; set; } // varchar(32)
		[Column, Nullable] public string Id       { get; set; } // varchar(32)
		[Column, Nullable] public string MBuySell { get; set; } // varchar(32)
	}

	[Table("OTC")]
	public partial class OTC
	{
		[Column, Nullable] public string Date          { get; set; } // varchar(32)
		[Column, Nullable] public string Type          { get; set; } // varchar(32)
		[Column, Nullable] public string Id            { get; set; } // varchar(32)
		[Column, Nullable] public string Name          { get; set; } // varchar(32)
		[Column, Nullable] public string Close         { get; set; } // varchar(32)
		[Column, Nullable] public string UpDown        { get; set; } // varchar(32)
		[Column, Nullable] public string Open          { get; set; } // varchar(32)
		[Column, Nullable] public string High          { get; set; } // varchar(32)
		[Column, Nullable] public string Low           { get; set; } // varchar(32)
		[Column, Nullable] public string DealVolume    { get; set; } // varchar(32)
		[Column, Nullable] public string DealPrice     { get; set; } // varchar(32)
		[Column, Nullable] public string DealNums      { get; set; } // varchar(32)
		[Column, Nullable] public string LastBuyPrice  { get; set; } // varchar(32)
		[Column, Nullable] public string LastSellPrice { get; set; } // varchar(32)
		[Column, Nullable] public string NowCapital    { get; set; } // varchar(32)
		[Column, Nullable] public string MaxPriceT     { get; set; } // varchar(32)
		[Column, Nullable] public string MinPriceT     { get; set; } // varchar(32)
		[Column, Nullable] public string TurnoverRate  { get; set; } // varchar(32)
	}

	[Table("OTCAlert")]
	public partial class OTCAlert
	{
		[Column, Nullable] public string Date { get; set; } // varchar(32)
		[Column, Nullable] public string Type { get; set; } // varchar(32)
		[Column, Nullable] public string Id   { get; set; } // varchar(32)
		[Column, Nullable] public string Name { get; set; } // varchar(32)
	}

	[Table("OTCBuySell")]
	public partial class OTCBuySell
	{
		[Column, Nullable] public string Date     { get; set; } // varchar(32)
		[Column, Nullable] public string Type     { get; set; } // varchar(32)
		[Column, Nullable] public string Id       { get; set; } // varchar(32)
		[Column, Nullable] public string MBuySell { get; set; } // varchar(32)
	}
}

#pragma warning restore 1591
